{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.compose.ui",
    "module": "ui-test-junit4",
    "version": "1.0.0-beta03",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.1",
      "buildId:": "7217131"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.compose.ui",
          "module": "ui-test",
          "version": {
            "requires": "1.0.0-beta03"
          }
        },
        {
          "group": "androidx.activity",
          "module": "activity",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.test.ext",
          "module": "junit",
          "version": {
            "requires": "1.1.2"
          }
        },
        {
          "group": "junit",
          "module": "junit",
          "version": {
            "requires": "4.12"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.31"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.31"
          }
        }
      ],
      "files": [
        {
          "name": "ui-test-junit4-1.0.0-beta03.aar",
          "url": "ui-test-junit4-1.0.0-beta03.aar",
          "size": 101815,
          "sha512": "b0d60b4b0b1bf2f35adcaa2eb2c422012a90edea5fd7d76cac6eb11d1eba9d87bfb029a37497ebf039915844b8934f55f9af1db9380185566ed2cd7b564e08b2",
          "sha256": "f376db003a6fea41a07d177763c06d4c97ae7745cf7129b48b37109ab6356c87",
          "sha1": "835de6b6993f9c88bc1cfd386a638fa09e2c65d2",
          "md5": "ee45498342af7f93001390bbb75ad5cb"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.compose.ui",
          "module": "ui-test",
          "version": {
            "requires": "1.0.0-beta03"
          }
        },
        {
          "group": "androidx.activity",
          "module": "activity",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.test.ext",
          "module": "junit",
          "version": {
            "requires": "1.1.2"
          }
        },
        {
          "group": "junit",
          "module": "junit",
          "version": {
            "requires": "4.12"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.31"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.31"
          }
        },
        {
          "group": "androidx.compose.animation",
          "module": "animation-core",
          "version": {
            "requires": "1.0.0-beta03"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-saveable",
          "version": {
            "requires": "1.0.0-beta03"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-common",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "androidx.test",
          "module": "core",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "androidx.test",
          "module": "monitor",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "androidx.test.espresso",
          "module": "espresso-core",
          "version": {
            "requires": "3.3.0"
          }
        },
        {
          "group": "androidx.test.espresso",
          "module": "espresso-idling-resource",
          "version": {
            "requires": "3.3.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.4.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-test",
          "version": {
            "requires": "1.4.1"
          }
        }
      ],
      "files": [
        {
          "name": "ui-test-junit4-1.0.0-beta03.aar",
          "url": "ui-test-junit4-1.0.0-beta03.aar",
          "size": 101815,
          "sha512": "b0d60b4b0b1bf2f35adcaa2eb2c422012a90edea5fd7d76cac6eb11d1eba9d87bfb029a37497ebf039915844b8934f55f9af1db9380185566ed2cd7b564e08b2",
          "sha256": "f376db003a6fea41a07d177763c06d4c97ae7745cf7129b48b37109ab6356c87",
          "sha1": "835de6b6993f9c88bc1cfd386a638fa09e2c65d2",
          "md5": "ee45498342af7f93001390bbb75ad5cb"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ui-test-junit4-1.0.0-beta03-sources.jar",
          "url": "ui-test-junit4-1.0.0-beta03-sources.jar",
          "size": 24651,
          "sha512": "983765bd2d1e590fbf9ee79836a8dc91d6358a52a1b558092e421c56fcf6975e7e0027b3696313ee06cee821ed60b65fda593b57295aff8ebcf12f57de56206b",
          "sha256": "4ef2d36a9b2d358fdbf5b88a8ee1faa26a812c8f3a62fbdbe423adb8998af4f8",
          "sha1": "15b8b8b868e22aa402b077188c99c2837f4c9d53",
          "md5": "9aceafec5554e3410107ae0914811bac"
        }
      ]
    }
  ]
}
