{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.hilt",
    "module": "hilt-compiler",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.1",
      "buildId:": "7309742"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "hilt-compiler-1.0.0.jar",
          "url": "hilt-compiler-1.0.0.jar",
          "size": 31917,
          "sha512": "582aff3b5b6e8ae862bd841647533363c0663b1f2c357550897b882844058de5c94b5a0ec3966f46ce73e601af8825bd2f7bccdd0421bb188d53303c5c54ab41",
          "sha256": "647c49239235e9ed031540b07da8003046a13da82983ab8b4b383c26b87b22a5",
          "sha1": "282fb739f492e9dd5b9dcf1bef8f8c9b7a2b5c18",
          "md5": "d45959f6b761cecb9889a109787308f9"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "com.google.auto",
          "module": "auto-common",
          "version": {
            "requires": "0.11"
          }
        },
        {
          "group": "com.squareup",
          "module": "javapoet",
          "version": {
            "requires": "1.13.0"
          }
        }
      ],
      "files": [
        {
          "name": "hilt-compiler-1.0.0.jar",
          "url": "hilt-compiler-1.0.0.jar",
          "size": 31917,
          "sha512": "582aff3b5b6e8ae862bd841647533363c0663b1f2c357550897b882844058de5c94b5a0ec3966f46ce73e601af8825bd2f7bccdd0421bb188d53303c5c54ab41",
          "sha256": "647c49239235e9ed031540b07da8003046a13da82983ab8b4b383c26b87b22a5",
          "sha1": "282fb739f492e9dd5b9dcf1bef8f8c9b7a2b5c18",
          "md5": "d45959f6b761cecb9889a109787308f9"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "hilt-compiler-1.0.0-sources.jar",
          "url": "hilt-compiler-1.0.0-sources.jar",
          "size": 11416,
          "sha512": "b92cb5e0bccb3f90ec5b57b10b4ee8c052bc7c144ec0eb8dada55a5aea2d4004d8f4b0665842a888d18bc6af484e91d2f4e8b9a37ae1bf6f2ecc8a0509c5489f",
          "sha256": "168131e8cecb127557db67cb049bbe190d3a4c95dfa21175a6c7799f142584e2",
          "sha1": "f6b60b8932064df71cb7c16952069c74188b5bc3",
          "md5": "fe2066b902540ba507cd053ce083ad21"
        }
      ]
    }
  ]
}
