{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.profileinstaller",
    "module": "profileinstaller",
    "version": "1.1.0-beta01",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.startup",
          "module": "startup-runtime",
          "version": {
            "requires": "1.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "profileinstaller-1.1.0-beta01.aar",
          "url": "profileinstaller-1.1.0-beta01.aar",
          "size": 29725,
          "sha512": "948e6145f8dd6fab5ca8a9f1c8f6a34e9be2193d3a5d5d3177aa80cf9ceff3f69af4f92b661820fd61897eafa749543e13dae09dac22d5c0d04380ff1d472d61",
          "sha256": "746231e14497157376a288d96932378c74568c725eb8ff300c728b61d60c6f3d",
          "sha1": "d1fb06d8797df9bc5acf7b527b972b2129dc1294",
          "md5": "0c6fc27a8ac3e6d0c8c0f551dc55b8fe"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.startup",
          "module": "startup-runtime",
          "version": {
            "requires": "1.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "profileinstaller-1.1.0-beta01.aar",
          "url": "profileinstaller-1.1.0-beta01.aar",
          "size": 29725,
          "sha512": "948e6145f8dd6fab5ca8a9f1c8f6a34e9be2193d3a5d5d3177aa80cf9ceff3f69af4f92b661820fd61897eafa749543e13dae09dac22d5c0d04380ff1d472d61",
          "sha256": "746231e14497157376a288d96932378c74568c725eb8ff300c728b61d60c6f3d",
          "sha1": "d1fb06d8797df9bc5acf7b527b972b2129dc1294",
          "md5": "0c6fc27a8ac3e6d0c8c0f551dc55b8fe"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "profileinstaller-1.1.0-beta01-sources.jar",
          "url": "profileinstaller-1.1.0-beta01-sources.jar",
          "size": 23193,
          "sha512": "109dbf0a477306c5d1fc654bbc81d34e79dccb6f78965574ce2684ce5ef19f63add0c711a2369a2aa9707958381973822369e011ead9ea3050c374d8853516e4",
          "sha256": "edb78f5df54627c30f43c4ef60830da0dc287b8db9fe3e5bb2ec3f2228b0e1b8",
          "sha1": "7c00ee42c12580060a08246d2fad929016883895",
          "md5": "db7ab1578f0f78cb9b6f530d4d3df0f5"
        }
      ]
    }
  ]
}
