{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.compose.foundation",
    "module": "foundation-layout",
    "version": "1.1.0-beta01",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.1.0-beta01"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-unit",
          "version": {
            "requires": "1.1.0-beta01"
          }
        }
      ],
      "files": [
        {
          "name": "foundation-layout-1.1.0-beta01.aar",
          "url": "foundation-layout-1.1.0-beta01.aar",
          "size": 316815,
          "sha512": "c1e9df12eeebfb50ed00ef8167b31bf11f406ec22e30811dd1953051caeeec85f6c521f2ebb9f64416f3cdbf1ed23e4cb01b59b034c087cad5e23924534ba06d",
          "sha256": "795c7ed698678f99e05c1e9fbe7a9a13b533b96a909198b936cce900dcb3a842",
          "sha1": "ac2bcc4c424609cb462e8ae1e49c6609ddeb2a71",
          "md5": "47481076a6e3d7a65bede9a4fdd661fe"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.1.0-beta01"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-unit",
          "version": {
            "requires": "1.1.0-beta01"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.1.0-beta01"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-util",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.5.31"
          }
        }
      ],
      "files": [
        {
          "name": "foundation-layout-1.1.0-beta01.aar",
          "url": "foundation-layout-1.1.0-beta01.aar",
          "size": 316815,
          "sha512": "c1e9df12eeebfb50ed00ef8167b31bf11f406ec22e30811dd1953051caeeec85f6c521f2ebb9f64416f3cdbf1ed23e4cb01b59b034c087cad5e23924534ba06d",
          "sha256": "795c7ed698678f99e05c1e9fbe7a9a13b533b96a909198b936cce900dcb3a842",
          "sha1": "ac2bcc4c424609cb462e8ae1e49c6609ddeb2a71",
          "md5": "47481076a6e3d7a65bede9a4fdd661fe"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "foundation-layout-1.1.0-beta01-sources.jar",
          "url": "foundation-layout-1.1.0-beta01-sources.jar",
          "size": 40939,
          "sha512": "c3053ef312e0b246f4cae54ce72512c6cd2fc583e284fa605e91671b0080e4937603f1d286231c997d45c73aea5e82b54f6b0caa45908d10263964393f3ec804",
          "sha256": "6c3f257f5313fa9274f5ef463ca498aca955780bdc389b8fb1fba72ffd9924c2",
          "sha1": "d61092a870344168c72f3b5198ef3ed7fb69ff17",
          "md5": "f0de4fb26263c8901f9a5430ddabf52f"
        }
      ]
    }
  ]
}
