{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.compose.animation",
    "module": "animation-core",
    "version": "1.0.0-beta03",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.1",
      "buildId:": "7217131"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.4.1"
          }
        }
      ],
      "files": [
        {
          "name": "animation-core-1.0.0-beta03.aar",
          "url": "animation-core-1.0.0-beta03.aar",
          "size": 254676,
          "sha512": "0f008d5767904a080f8ab99782633f92631c7f9c333cf1eb5afcafdd474d6690cb0de7f5c173b0c2e42fef1448d151e747b4eebb65dfdffec1a665765f2250a0",
          "sha256": "4626086855eb6582dda9c3050c05bb56632f5a0308a3bb71a0f58def958602ca",
          "sha1": "e4e11fedf1f83f80345691143b0f4c1ce59563dc",
          "md5": "c3ef44fc9a7c786af40114535648fd0b"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.4.1"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.0.0-beta03"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-unit",
          "version": {
            "requires": "1.0.0-beta03"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-util",
          "version": {
            "requires": "1.0.0-beta03"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.31"
          }
        }
      ],
      "files": [
        {
          "name": "animation-core-1.0.0-beta03.aar",
          "url": "animation-core-1.0.0-beta03.aar",
          "size": 254676,
          "sha512": "0f008d5767904a080f8ab99782633f92631c7f9c333cf1eb5afcafdd474d6690cb0de7f5c173b0c2e42fef1448d151e747b4eebb65dfdffec1a665765f2250a0",
          "sha256": "4626086855eb6582dda9c3050c05bb56632f5a0308a3bb71a0f58def958602ca",
          "sha1": "e4e11fedf1f83f80345691143b0f4c1ce59563dc",
          "md5": "c3ef44fc9a7c786af40114535648fd0b"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "animation-core-1.0.0-beta03-sources.jar",
          "url": "animation-core-1.0.0-beta03-sources.jar",
          "size": 68093,
          "sha512": "8b4447bb72d664b00e4af10ab8576de36f6bb8c387f22b24f7f41a39240bef181171ec0fe2c02cc390c8e1a5c46043b7a2455ab25e450b25b5092174bf859123",
          "sha256": "40b4025a8bcebf1cb66bde8c9e9f75bc13fc561548e23e3f18b35e80d79ddd9a",
          "sha1": "df1c5d6d90fa0aa84b4f5dd5c535cc70bd42af82",
          "md5": "a24fe6bfa82749fbbdc83c6be22e0af8"
        }
      ]
    }
  ]
}
