{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.compose.animation",
    "module": "animation-core",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "animation-core-1.0.0.aar",
          "url": "animation-core-1.0.0.aar",
          "size": 1288376,
          "sha512": "e720041097fe2baa1b14bc06a6d17f6aba7fef5e3781ef0277399ed1282c2935a4e729bb81a611da1cea2f1b5c7c6f8f50d7c74ee66926cd46f973c1c7fd6539",
          "sha256": "5365c3e79957a0e04ced9889d4e7d2ad4aa7b5defdc239b9b4dcee12ac52b7c0",
          "sha1": "a2c7e306f07ab68d3dc4c677156b50b04cca2e8d",
          "md5": "ae656fe8a05d947093b56f6c43b9063d"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-unit",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-util",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.5.10"
          }
        }
      ],
      "files": [
        {
          "name": "animation-core-1.0.0.aar",
          "url": "animation-core-1.0.0.aar",
          "size": 1288376,
          "sha512": "e720041097fe2baa1b14bc06a6d17f6aba7fef5e3781ef0277399ed1282c2935a4e729bb81a611da1cea2f1b5c7c6f8f50d7c74ee66926cd46f973c1c7fd6539",
          "sha256": "5365c3e79957a0e04ced9889d4e7d2ad4aa7b5defdc239b9b4dcee12ac52b7c0",
          "sha1": "a2c7e306f07ab68d3dc4c677156b50b04cca2e8d",
          "md5": "ae656fe8a05d947093b56f6c43b9063d"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "animation-core-1.0.0-sources.jar",
          "url": "animation-core-1.0.0-sources.jar",
          "size": 69581,
          "sha512": "63939bdc4a1818d34b299bbdc3cad39362e3072529e828e64740714fcb178815b0b6ba0d75b91e542e276598dce24f0667efd29680c8ed47d7babb1a3d1ae387",
          "sha256": "bf0748117142aa4525ccf8c74b83a6be0d98ca7c7c68e9919043f44a8a8757b4",
          "sha1": "c230b84f27ee79adf5e8d6115cdf6c3f89f5b7fd",
          "md5": "589f869157655564c0a63445369bf2fe"
        }
      ]
    }
  ]
}
