{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kotlinx-coroutines-core/1.4.3/kotlinx-coroutines-core-1.4.3.module",
    "group": "org.jetbrains.kotlinx",
    "module": "kotlinx-coroutines-core",
    "version": "1.4.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "3wriqa3ax5c4rcfwqabmdy3weu"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.30"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.30"
          }
        }
      ],
      "files": [
        {
          "name": "kotlinx-coroutines-core-jvm-1.4.3.jar",
          "url": "kotlinx-coroutines-core-jvm-1.4.3.jar",
          "size": 1656936,
          "sha512": "38af00a5963e21ea76ee2529a30102af636f4cb51b86ec1cfd3b4aef31dee71a4afe149268d523e2434e327e8ebad2f71f1439ace5826b583cba92828ccbfd8c",
          "sha256": "f7be08ddf86bd88020da7b78adbf44228799cca54d5c0c4396d850bc66725163",
          "sha1": "1051e11eb789ed1df93412bebe0f06e9d29160e4",
          "md5": "156008c5a57a5176eaf005fea98a755a"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.30"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.30"
          }
        }
      ],
      "files": [
        {
          "name": "kotlinx-coroutines-core-jvm-1.4.3.jar",
          "url": "kotlinx-coroutines-core-jvm-1.4.3.jar",
          "size": 1656936,
          "sha512": "38af00a5963e21ea76ee2529a30102af636f4cb51b86ec1cfd3b4aef31dee71a4afe149268d523e2434e327e8ebad2f71f1439ace5826b583cba92828ccbfd8c",
          "sha256": "f7be08ddf86bd88020da7b78adbf44228799cca54d5c0c4396d850bc66725163",
          "sha1": "1051e11eb789ed1df93412bebe0f06e9d29160e4",
          "md5": "156008c5a57a5176eaf005fea98a755a"
        }
      ]
    },
    {
      "name": "metadataApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "available-at": {
        "url": "../../kotlinx-coroutines-core/1.4.3/kotlinx-coroutines-core-1.4.3.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-coroutines-core",
        "version": "1.4.3"
      }
    },
    {
      "name": "commonMainMetadataElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "available-at": {
        "url": "../../kotlinx-coroutines-core/1.4.3/kotlinx-coroutines-core-1.4.3.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-coroutines-core",
        "version": "1.4.3"
      }
    }
  ]
}
