{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.compose.ui",
    "module": "ui-geometry",
    "version": "1.1.0-beta01",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "ui-geometry-1.1.0-beta01.aar",
          "url": "ui-geometry-1.1.0-beta01.aar",
          "size": 37364,
          "sha512": "3cb49cfdf5909b7fa1bb8032c9f8b9e2c21ae883249b6f1d4eee734581e069db56b5f7bb01ac0db5f179a4762a01b22e83d029a8f004e1c4f9ccb4ac41b9f8aa",
          "sha256": "14fb48fb3285d9b97f29b6ae84530eeed86c650ea7555642551654f6c747d046",
          "sha1": "d19f03add9e2973d4253dc525a234254f522e89a",
          "md5": "c8049ec5b79388a1142de8ebc3040a65"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.1.0-beta01"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-util",
          "version": {
            "requires": "1.1.0-beta01"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.5.31"
          }
        }
      ],
      "files": [
        {
          "name": "ui-geometry-1.1.0-beta01.aar",
          "url": "ui-geometry-1.1.0-beta01.aar",
          "size": 37364,
          "sha512": "3cb49cfdf5909b7fa1bb8032c9f8b9e2c21ae883249b6f1d4eee734581e069db56b5f7bb01ac0db5f179a4762a01b22e83d029a8f004e1c4f9ccb4ac41b9f8aa",
          "sha256": "14fb48fb3285d9b97f29b6ae84530eeed86c650ea7555642551654f6c747d046",
          "sha1": "d19f03add9e2973d4253dc525a234254f522e89a",
          "md5": "c8049ec5b79388a1142de8ebc3040a65"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ui-geometry-1.1.0-beta01-sources.jar",
          "url": "ui-geometry-1.1.0-beta01-sources.jar",
          "size": 17994,
          "sha512": "8b2e99a97d5c4bc38950079c203dcab2870dad2988b5546f8e105c969bbabe20fef5838d7527eca1cab00d4d0a97ac4bef67a77d5947e0ce24da4e0002cb5c6d",
          "sha256": "8fe9156c7fc2ba3cffb84de46b461e8183a02b6fd2e054ee2fd1cd7574e36fab",
          "sha1": "62cddbba1976f50b4fa1b8668294631a1ee0f568",
          "md5": "015df06b2ca2be7fa86ea9722f286938"
        }
      ]
    }
  ]
}
