{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.compose.ui",
    "module": "ui-text",
    "version": "1.1.0-beta01",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.compose.ui",
          "module": "ui-graphics",
          "version": {
            "requires": "1.1.0-beta01"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-unit",
          "version": {
            "requires": "1.1.0-beta01"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "ui-text-1.1.0-beta01.aar",
          "url": "ui-text-1.1.0-beta01.aar",
          "size": 455235,
          "sha512": "02598fa4a3de8a8e7e51fe1defc2661f6cd16e1c1957cf9b1c0c9a80f57e6a4931ed214304529dcfc27963f0bb65b91bb84ba9a9346f5b6ce0a09983c508001a",
          "sha256": "3cab9aba97f31d09b6f8f2c3d29d089f7533227c50a87bbc7eab4153c037da67",
          "sha1": "af639156678cfd064d9a854c3e43d5a87773e551",
          "md5": "6217e035427c16667bbb1ca9b1cce23e"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.compose.ui",
          "module": "ui-graphics",
          "version": {
            "requires": "1.1.0-beta01"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-unit",
          "version": {
            "requires": "1.1.0-beta01"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.5.31"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.1.0-beta01"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-saveable",
          "version": {
            "requires": "1.1.0-beta01"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-util",
          "version": {
            "requires": "1.1.0-beta01"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.5.31"
          }
        },
        {
          "group": "androidx.collection",
          "module": "collection",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "ui-text-1.1.0-beta01.aar",
          "url": "ui-text-1.1.0-beta01.aar",
          "size": 455235,
          "sha512": "02598fa4a3de8a8e7e51fe1defc2661f6cd16e1c1957cf9b1c0c9a80f57e6a4931ed214304529dcfc27963f0bb65b91bb84ba9a9346f5b6ce0a09983c508001a",
          "sha256": "3cab9aba97f31d09b6f8f2c3d29d089f7533227c50a87bbc7eab4153c037da67",
          "sha1": "af639156678cfd064d9a854c3e43d5a87773e551",
          "md5": "6217e035427c16667bbb1ca9b1cce23e"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ui-text-1.1.0-beta01-sources.jar",
          "url": "ui-text-1.1.0-beta01-sources.jar",
          "size": 173486,
          "sha512": "bb5fe4b6c773e6ce40319fa7b0a07036a35d1a7f252ce17625936afcc8e5110bc27f31bbe9de7e1da1b027bfa30fe3208f88182f1a8cd8a1c7c121911b9bdce6",
          "sha256": "587a992e9eeb3288fd3203b69b20eeb6d4e8db29dd46625e9b584b7c6c96387d",
          "sha1": "ca17b10d3a6d41639cdd0b58cd0b5dcc58ed104a",
          "md5": "85ce2e1a892db3378662ecac80bb6444"
        }
      ]
    }
  ]
}
