{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.navigation",
    "module": "navigation-runtime-ktx",
    "version": "2.5.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5-20220421031748+0000"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.navigation",
          "module": "navigation-common-ktx",
          "version": {
            "requires": "2.5.3"
          },
          "reason": "Mirror navigation-runtime dependency graph for -ktx artifacts"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-runtime",
          "version": {
            "requires": "2.5.3"
          }
        }
      ],
      "files": [
        {
          "name": "navigation-runtime-ktx-2.5.3.aar",
          "url": "navigation-runtime-ktx-2.5.3.aar",
          "size": 1769,
          "sha512": "8b4402118f3f2d33c9005abb38da1ce55a544455dfefba5ad6c694754965cee3c8b20157e09475335970f2aa17e33b34618b5eb831992ee40ac91932a104ebb9",
          "sha256": "9ab94a34966c5501fac62979b96a5d64d1325b62caf707358616cf24df86caae",
          "sha1": "88d4a8375106f400e0bbe17d28432470449c23a6",
          "md5": "c7d95512ed298b5a67b48431d95000a5"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.navigation",
          "module": "navigation-common-ktx",
          "version": {
            "requires": "2.5.3"
          },
          "reason": "Mirror navigation-runtime dependency graph for -ktx artifacts"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-runtime",
          "version": {
            "requires": "2.5.3"
          }
        }
      ],
      "files": [
        {
          "name": "navigation-runtime-ktx-2.5.3.aar",
          "url": "navigation-runtime-ktx-2.5.3.aar",
          "size": 1769,
          "sha512": "8b4402118f3f2d33c9005abb38da1ce55a544455dfefba5ad6c694754965cee3c8b20157e09475335970f2aa17e33b34618b5eb831992ee40ac91932a104ebb9",
          "sha256": "9ab94a34966c5501fac62979b96a5d64d1325b62caf707358616cf24df86caae",
          "sha1": "88d4a8375106f400e0bbe17d28432470449c23a6",
          "md5": "c7d95512ed298b5a67b48431d95000a5"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "navigation-runtime-ktx-2.5.3-sources.jar",
          "url": "navigation-runtime-ktx-2.5.3-sources.jar",
          "size": 261,
          "sha512": "747d2f00a7f5f379582e33e452f30f3a25732a510971d9ed5161355bf7ef0fc507fef30883960dbfc780d36b6e8215fba01086b4ee053358805686e2f2c1aa85",
          "sha256": "69e1a62e5752ca3f43fb1607f161379bbe88b64af89c1a543c126160adf7cc53",
          "sha1": "5b8f86fea035328fc9e8c660773037a3401ce25f",
          "md5": "e7e9f45eb9d74540092920528bb0abf0"
        }
      ]
    }
  ]
}