{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.compose.material",
    "module": "material",
    "version": "1.1.0-beta01",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.compose.animation",
          "module": "animation-core",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.1.0-beta01"
          }
        },
        {
          "group": "androidx.compose.material",
          "module": "material-icons-core",
          "version": {
            "requires": "1.1.0-beta01"
          }
        },
        {
          "group": "androidx.compose.material",
          "module": "material-ripple",
          "version": {
            "requires": "1.1.0-beta01"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.1.0-beta01"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.1.0-beta01"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-text",
          "version": {
            "requires": "1.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "material-1.1.0-beta01.aar",
          "url": "material-1.1.0-beta01.aar",
          "size": 2444629,
          "sha512": "56b95ad78f4b4658bf5b32d51fa4b49dbf8388035e8b663002d9b6dcf7f21c9cd16af41d9c858eea0abac99963d981813871a894d3010d0f8f60cbd7af61d991",
          "sha256": "453618f67c8f88d00115216a1358c7e4a3f6e49bfecf7f391187dbf9c7653122",
          "sha1": "b08f9b4bed8bf0d7fb3e342d90b36a4e0829c552",
          "md5": "df81b218f85a7e2b22123d751c028ff4"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.compose.animation",
          "module": "animation-core",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.1.0-beta01"
          }
        },
        {
          "group": "androidx.compose.material",
          "module": "material-icons-core",
          "version": {
            "requires": "1.1.0-beta01"
          }
        },
        {
          "group": "androidx.compose.material",
          "module": "material-ripple",
          "version": {
            "requires": "1.1.0-beta01"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.1.0-beta01"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.1.0-beta01"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-text",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.5.31"
          }
        },
        {
          "group": "androidx.compose.animation",
          "module": "animation",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.compose.foundation",
          "module": "foundation-layout",
          "version": {
            "requires": "1.1.0-beta01"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-util",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.savedstate",
          "module": "savedstate",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel",
          "version": {
            "requires": "2.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "material-1.1.0-beta01.aar",
          "url": "material-1.1.0-beta01.aar",
          "size": 2444629,
          "sha512": "56b95ad78f4b4658bf5b32d51fa4b49dbf8388035e8b663002d9b6dcf7f21c9cd16af41d9c858eea0abac99963d981813871a894d3010d0f8f60cbd7af61d991",
          "sha256": "453618f67c8f88d00115216a1358c7e4a3f6e49bfecf7f391187dbf9c7653122",
          "sha1": "b08f9b4bed8bf0d7fb3e342d90b36a4e0829c552",
          "md5": "df81b218f85a7e2b22123d751c028ff4"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "material-1.1.0-beta01-sources.jar",
          "url": "material-1.1.0-beta01-sources.jar",
          "size": 186949,
          "sha512": "0b46e72518fe134b4edce6eb9fbdf27cc055cf0c097e5325d820942466555190b18b5966183b2bdbbb4ee137d74b7543b88f7f66c1aeda7d1d5d1552cb1dc9a9",
          "sha256": "84c66b579d0281708d8c66c2d1f9102d094340ce9be3670e966690f0a681abb3",
          "sha1": "b8a414ecfb2743d42fc35adb822f17db34653d20",
          "md5": "c2d943edad529b1259c5376cbf0c7287"
        }
      ]
    }
  ]
}
