{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.lifecycle",
    "module": "lifecycle-viewmodel-savedstate",
    "version": "2.5.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata-core",
          "version": {
            "requires": "2.5.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel",
          "version": {
            "requires": "2.5.0"
          }
        },
        {
          "group": "androidx.savedstate",
          "module": "savedstate",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.21"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "lifecycle-viewmodel-savedstate-2.5.0.aar",
          "url": "lifecycle-viewmodel-savedstate-2.5.0.aar",
          "size": 34933,
          "sha512": "915f94d0986dc2fc9d94a2347ab3d70dcb37cb23a8a890d501000799df3950d3281eff677ad96700f49d5d5a676059eb614e873cb4ea4735a2e8338ad8aabc85",
          "sha256": "b6a0797ce98b851655c44c1f0025cb42327de479273ae0af0b7e3227561415ae",
          "sha1": "890d51ee22f2d4e59ce8470a764d2d97c4d8244a",
          "md5": "8f1575e4f3b9f90063871db62e21b149"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata-core",
          "version": {
            "requires": "2.5.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel",
          "version": {
            "requires": "2.5.0"
          }
        },
        {
          "group": "androidx.savedstate",
          "module": "savedstate",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.21"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "lifecycle-viewmodel-savedstate-2.5.0.aar",
          "url": "lifecycle-viewmodel-savedstate-2.5.0.aar",
          "size": 34933,
          "sha512": "915f94d0986dc2fc9d94a2347ab3d70dcb37cb23a8a890d501000799df3950d3281eff677ad96700f49d5d5a676059eb614e873cb4ea4735a2e8338ad8aabc85",
          "sha256": "b6a0797ce98b851655c44c1f0025cb42327de479273ae0af0b7e3227561415ae",
          "sha1": "890d51ee22f2d4e59ce8470a764d2d97c4d8244a",
          "md5": "8f1575e4f3b9f90063871db62e21b149"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "lifecycle-viewmodel-savedstate-2.5.0-sources.jar",
          "url": "lifecycle-viewmodel-savedstate-2.5.0-sources.jar",
          "size": 15813,
          "sha512": "1259b4b87e5a1f195e60c9ae54d9a044385adb5f72e6cbd57c69ca9f10bc3b406b880848c367adb9f29ebfe193d79c44a22a001e77ca0b3ed11f6e0ca44be14e",
          "sha256": "5cf43d3c8f67295f0f8330d9442ab0d871bef16d12f47817ecb517c373bbd980",
          "sha1": "011f7a8fab7793634b9cc07891180c35fbf4315c",
          "md5": "11e134c252cf46c84114a198fc48e3e2"
        }
      ]
    }
  ]
}