{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.compose.ui",
    "module": "ui-util",
    "version": "1.1.0-beta01",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "ui-util-1.1.0-beta01.aar",
          "url": "ui-util-1.1.0-beta01.aar",
          "size": 7864,
          "sha512": "28c4d9f2ef431dccb3c4e14c7e4910a362ffaa3553a9a4901af409394c4ac362fa2a10fd1ba6545d812a2dba0f780f7ec4c34f62d28cb8666191c0d37e1d2405",
          "sha256": "124f134e8e0601d735f0099cf4365cad6143b303c4c2a1f9fd9330a37cd8f6b7",
          "sha1": "295867825aa87631bb7ce9e7ed903321e189d449",
          "md5": "fc30d915671e11d9564a35e1a72d70b0"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.5.31"
          }
        }
      ],
      "files": [
        {
          "name": "ui-util-1.1.0-beta01.aar",
          "url": "ui-util-1.1.0-beta01.aar",
          "size": 7864,
          "sha512": "28c4d9f2ef431dccb3c4e14c7e4910a362ffaa3553a9a4901af409394c4ac362fa2a10fd1ba6545d812a2dba0f780f7ec4c34f62d28cb8666191c0d37e1d2405",
          "sha256": "124f134e8e0601d735f0099cf4365cad6143b303c4c2a1f9fd9330a37cd8f6b7",
          "sha1": "295867825aa87631bb7ce9e7ed903321e189d449",
          "md5": "fc30d915671e11d9564a35e1a72d70b0"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ui-util-1.1.0-beta01-sources.jar",
          "url": "ui-util-1.1.0-beta01-sources.jar",
          "size": 4574,
          "sha512": "0d0d4178392cad87a78875b6d4cfd2aa27860ddfc0115c3a7f13003e7834503f32697f885b0c1b4aad56d409e258480b0e891e0711fe019028bc96866f33be6e",
          "sha256": "c72c6cf6834497e42f09c61f4e3e17a8bdc1b2add6dce25b546fbe6176322b34",
          "sha1": "69426082fe7d7ebbd25c1f8f755d2ee2b65b46da",
          "md5": "26e3ab71e8414dd37d17637ab86d2d3d"
        }
      ]
    }
  ]
}
