{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.compose.ui",
    "module": "ui-unit",
    "version": "1.1.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.compose.ui",
          "module": "ui-geometry",
          "version": {
            "requires": "1.1.1"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "ui-unit-1.1.1.aar",
          "url": "ui-unit-1.1.1.aar",
          "size": 65035,
          "sha512": "11e43e771bae03859003b3f6cea316675e4fd2da3d0e37dad47eabd26313110f60f6acdb6f03dc1c4926d93e1117d0810322bf85bb1f9aad495e9f0b6c123018",
          "sha256": "35b1d8f7f460874dde09fd7e630cd44052913695298076fc62de91a4fe1345a7",
          "sha1": "bc1108e8e9e70482f9610d9b6ef18ef4fc919758",
          "md5": "b1ee7ebd28ac8e83dd52ab0e19c64591"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.compose.ui",
          "module": "ui-geometry",
          "version": {
            "requires": "1.1.1"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.1.1"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-util",
          "version": {
            "requires": "1.1.1"
          }
        }
      ],
      "files": [
        {
          "name": "ui-unit-1.1.1.aar",
          "url": "ui-unit-1.1.1.aar",
          "size": 65035,
          "sha512": "11e43e771bae03859003b3f6cea316675e4fd2da3d0e37dad47eabd26313110f60f6acdb6f03dc1c4926d93e1117d0810322bf85bb1f9aad495e9f0b6c123018",
          "sha256": "35b1d8f7f460874dde09fd7e630cd44052913695298076fc62de91a4fe1345a7",
          "sha1": "bc1108e8e9e70482f9610d9b6ef18ef4fc919758",
          "md5": "b1ee7ebd28ac8e83dd52ab0e19c64591"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ui-unit-1.1.1-sources.jar",
          "url": "ui-unit-1.1.1-sources.jar",
          "size": 23326,
          "sha512": "76d343176a2ffdbf575b9f59577c62dd4092dabc18072b23bf64b910156cf5d179adfc3f76e2bbd7846d861cea69d8ce6ae7180aabcac11c9c6293c1e83ef8da",
          "sha256": "918a3c500e20a0bf2cb92c0723a6ab0483bce7c75a59e5ebd29566133f996e0d",
          "sha1": "e7d13bf2b7360ed393166e3f825368e71e9fcd3f",
          "md5": "a142c5aa2793c83c1db39421e9d41708"
        }
      ]
    }
  ]
}
