{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.lifecycle",
    "module": "lifecycle-livedata-ktx",
    "version": "2.5.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata",
          "version": {
            "requires": "2.5.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata-core-ktx",
          "version": {
            "requires": "2.5.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.21"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "lifecycle-livedata-ktx-2.5.0.aar",
          "url": "lifecycle-livedata-ktx-2.5.0.aar",
          "size": 40750,
          "sha512": "54bbd58cd99eee3f1b48cfa7640f5a72c4325a40ea1808eb3e69b5228ded58ae4ad9c07c069b4e15e5c14cb677b5b009c641b056041d721447625ad1081b8c51",
          "sha256": "1f147d769ef4b602c682521e6c8f7f4f65297223b81d929ac378051236f7e621",
          "sha1": "5790f3225d67cf5949cc4834037ddfbe5c80020f",
          "md5": "aa4473a6c4ec3f7ef786ee8142c2cc61"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata",
          "version": {
            "requires": "2.5.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata-core-ktx",
          "version": {
            "requires": "2.5.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.21"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "lifecycle-livedata-ktx-2.5.0.aar",
          "url": "lifecycle-livedata-ktx-2.5.0.aar",
          "size": 40750,
          "sha512": "54bbd58cd99eee3f1b48cfa7640f5a72c4325a40ea1808eb3e69b5228ded58ae4ad9c07c069b4e15e5c14cb677b5b009c641b056041d721447625ad1081b8c51",
          "sha256": "1f147d769ef4b602c682521e6c8f7f4f65297223b81d929ac378051236f7e621",
          "sha1": "5790f3225d67cf5949cc4834037ddfbe5c80020f",
          "md5": "aa4473a6c4ec3f7ef786ee8142c2cc61"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "lifecycle-livedata-ktx-2.5.0-sources.jar",
          "url": "lifecycle-livedata-ktx-2.5.0-sources.jar",
          "size": 8725,
          "sha512": "821c6091de18f97dcb9e34631e9fa9f04886992595f01391ffe88a30401bafe2c26d03f6c6514a86d38f722ec3d6448d71275075753e6deb1e7999f63b33d89e",
          "sha256": "93b88aed20951cf9ffdc604ae665414bca0811c069986c339d0d1991861fa956",
          "sha1": "9017d4f6a545e0fd90d4a40bef15b517fa32fbcb",
          "md5": "edf93d3aa22eb5d1ac37890a66fb05a6"
        }
      ]
    }
  ]
}