{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.compose.animation",
    "module": "animation-core",
    "version": "1.1.0-beta01",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.5.2"
          }
        }
      ],
      "files": [
        {
          "name": "animation-core-1.1.0-beta01.aar",
          "url": "animation-core-1.1.0-beta01.aar",
          "size": 1297074,
          "sha512": "46a554a0d124b4f47799d393f64839b6cf25dcd566e6f9643b34df5e376f47fcc46792a0aaee434eaeaa3f547b6f1efcaa68fac509e741c0097451eb23a8e711",
          "sha256": "0a3a7e2a14bf630a4a65296be232e4d167aef8a7cb83a0cd49a62cfe88cd14f9",
          "sha1": "4aeeed07eace61bf3836b6fea83429692c6169fc",
          "md5": "9aa577c02c99ba2c6b4062b83eb24828"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.5.2"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.1.0-beta01"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-unit",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-util",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.5.31"
          }
        }
      ],
      "files": [
        {
          "name": "animation-core-1.1.0-beta01.aar",
          "url": "animation-core-1.1.0-beta01.aar",
          "size": 1297074,
          "sha512": "46a554a0d124b4f47799d393f64839b6cf25dcd566e6f9643b34df5e376f47fcc46792a0aaee434eaeaa3f547b6f1efcaa68fac509e741c0097451eb23a8e711",
          "sha256": "0a3a7e2a14bf630a4a65296be232e4d167aef8a7cb83a0cd49a62cfe88cd14f9",
          "sha1": "4aeeed07eace61bf3836b6fea83429692c6169fc",
          "md5": "9aa577c02c99ba2c6b4062b83eb24828"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "animation-core-1.1.0-beta01-sources.jar",
          "url": "animation-core-1.1.0-beta01-sources.jar",
          "size": 71699,
          "sha512": "dc110fd5f022aabe85dddcb1140058477f205f884d525374f39f80bcd91bbfec278836e196c1efcd911dbb6029e5971b76890cac2c13421c4d3afd700d51df26",
          "sha256": "e336c8b1f185f18d9efa07614c50c37d47446d7b75236e8f80f6fa1b0bafee8c",
          "sha1": "f1f925326492810ddf42eb6a84d1890b81d18f84",
          "md5": "2b0e94d93a01bd75e915d26850db8d30"
        }
      ]
    }
  ]
}
