{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.compose.runtime",
    "module": "runtime",
    "version": "1.0.0-beta03",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.1",
      "buildId:": "7217131"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.4.1"
          }
        }
      ],
      "files": [
        {
          "name": "runtime-1.0.0-beta03.aar",
          "url": "runtime-1.0.0-beta03.aar",
          "size": 1559367,
          "sha512": "fefc40bbce003ea7fe79af60af0a3f951af2702ff50c63f40a70a39bad6589e4d2926e15cabb56db7b10d69a1335178e2fb20122ebf1982a023c8d87702d304a",
          "sha256": "5ab7662bac71ba3f3f48287ec045af083c5b5806dfbf2717662705edd33173de",
          "sha1": "6fb15133e471c3140cf1f0127ed49bd71184e7a8",
          "md5": "c4ff8da13978d5bcc5ed7d874b2b6095"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.4.1"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-collections-immutable-jvm",
          "version": {
            "requires": "0.3.3"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.31"
          }
        }
      ],
      "files": [
        {
          "name": "runtime-1.0.0-beta03.aar",
          "url": "runtime-1.0.0-beta03.aar",
          "size": 1559367,
          "sha512": "fefc40bbce003ea7fe79af60af0a3f951af2702ff50c63f40a70a39bad6589e4d2926e15cabb56db7b10d69a1335178e2fb20122ebf1982a023c8d87702d304a",
          "sha256": "5ab7662bac71ba3f3f48287ec045af083c5b5806dfbf2717662705edd33173de",
          "sha1": "6fb15133e471c3140cf1f0127ed49bd71184e7a8",
          "md5": "c4ff8da13978d5bcc5ed7d874b2b6095"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "runtime-1.0.0-beta03-sources.jar",
          "url": "runtime-1.0.0-beta03-sources.jar",
          "size": 166039,
          "sha512": "96eacf88ac06d829cd9768150d35482f0fb1e5a7367a6d54a6debd470fb10ad7bed049dc11295f3b3d00d539bcc92415f0518b032f5d3016b1773f9f5ac6c849",
          "sha256": "8c3fc37d393873e96282ae3ebdf00b72b8da4651752e5ed167b69617bcb5a2dc",
          "sha1": "69a338b3831d814cc45e2cd8c663b59a7f25c355",
          "md5": "2fb2603366dcef9f284c6d558d8fe169"
        }
      ]
    }
  ]
}
