{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.compose.ui",
    "module": "ui-text",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.compose.ui",
          "module": "ui-graphics",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-unit",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "ui-text-1.0.0.aar",
          "url": "ui-text-1.0.0.aar",
          "size": 458345,
          "sha512": "bc5bc31e2a4907f7968fd37d4109ae97c1ee4c4e44a58bb452dfa6d670d0711d328c52e0907bb8d960878444caac7174a8c2a52316ff4ec3535ea70ce55b6c51",
          "sha256": "ee38b166b926984393b79936617e77c9ae212a7c250d0cc125fcdb22e83261b0",
          "sha1": "b81967b716906f82e9fb3ccf809c3f880e6ec705",
          "md5": "4192141661db2eb4f19c4663a4555ca4"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.compose.ui",
          "module": "ui-graphics",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-unit",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.5.10"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-saveable",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-util",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.5.10"
          }
        },
        {
          "group": "androidx.collection",
          "module": "collection",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "ui-text-1.0.0.aar",
          "url": "ui-text-1.0.0.aar",
          "size": 458345,
          "sha512": "bc5bc31e2a4907f7968fd37d4109ae97c1ee4c4e44a58bb452dfa6d670d0711d328c52e0907bb8d960878444caac7174a8c2a52316ff4ec3535ea70ce55b6c51",
          "sha256": "ee38b166b926984393b79936617e77c9ae212a7c250d0cc125fcdb22e83261b0",
          "sha1": "b81967b716906f82e9fb3ccf809c3f880e6ec705",
          "md5": "4192141661db2eb4f19c4663a4555ca4"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ui-text-1.0.0-sources.jar",
          "url": "ui-text-1.0.0-sources.jar",
          "size": 172782,
          "sha512": "439c3de871dbf85920b37423112802f5cfaeab3fc48c900b66b02938549d02485a47f983acb27bb2a2500250b1e8c4fc19ac6c0d306c11f202544a5d960e0c7b",
          "sha256": "2a79c0efde7fa47a05030197ee438a792528d652bcebb863f90dd0a001b42e48",
          "sha1": "4536a690eae671aebd209959855372e537aee7d5",
          "md5": "e0b233deda01d1f7f83f5155a2769d4b"
        }
      ]
    }
  ]
}
