{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.compose.material",
    "module": "material-ripple",
    "version": "1.1.0-beta01",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.1.0-beta01"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.1.0-beta01"
          }
        }
      ],
      "files": [
        {
          "name": "material-ripple-1.1.0-beta01.aar",
          "url": "material-ripple-1.1.0-beta01.aar",
          "size": 73632,
          "sha512": "090082b390c861f44025af8fabb2945b6ed470214174337bb6b42c24940bceb3dbfada6d5c16872a2eb8ad254e52d5ef0b723436833c9a622389cb0b6abc7a3c",
          "sha256": "6b36820c2c9fa6c21e49cc94effae179dc666af8928d9e70beb27b6964217415",
          "sha1": "70b5b3a6da87307275e527fb92ada801e06aba23",
          "md5": "41242b7ba8c295bc3064f7ef927b15dc"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.1.0-beta01"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.1.0-beta01"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.5.31"
          }
        },
        {
          "group": "androidx.compose.animation",
          "module": "animation",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-util",
          "version": {
            "requires": "1.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "material-ripple-1.1.0-beta01.aar",
          "url": "material-ripple-1.1.0-beta01.aar",
          "size": 73632,
          "sha512": "090082b390c861f44025af8fabb2945b6ed470214174337bb6b42c24940bceb3dbfada6d5c16872a2eb8ad254e52d5ef0b723436833c9a622389cb0b6abc7a3c",
          "sha256": "6b36820c2c9fa6c21e49cc94effae179dc666af8928d9e70beb27b6964217415",
          "sha1": "70b5b3a6da87307275e527fb92ada801e06aba23",
          "md5": "41242b7ba8c295bc3064f7ef927b15dc"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "material-ripple-1.1.0-beta01-sources.jar",
          "url": "material-ripple-1.1.0-beta01-sources.jar",
          "size": 21691,
          "sha512": "1b90df22733378bbf14bf73f1e44954476a67b9fbd22ad2d14e57f4970e2c06bc85a1a70d4b9ae85b83e7eb760ce9ba9fc13a5c61f68ce60afb64335b97022fa",
          "sha256": "ed1dc4e848d69095c883c2e02a0794f0adf34b021762895f5ac010dc74a67e15",
          "sha1": "17dc970b3b9979e18c1401c0d30c381a1d4eeff1",
          "md5": "3829807753b151eda51c1840b346b97e"
        }
      ]
    }
  ]
}
