{
  "formatVersion": "1.1",
  "component": {
    "group": "io.mockk",
    "module": "mockk",
    "version": "1.12.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.2"
    }
  },
  "variants": [
    {
      "name": "-api",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "io.mockk",
          "module": "mockk-dsl-jvm",
          "version": {
            "requires": "1.12.2"
          }
        },
        {
          "group": "io.mockk",
          "module": "mockk-common",
          "version": {
            "requires": "1.12.2"
          }
        }
      ],
      "files": [
        {
          "name": "mockk-1.12.2.jar",
          "url": "mockk-1.12.2.jar",
          "size": 535748,
          "sha512": "a9002c60c58d91238a242fe2b852a1972accbf350403c0ea6e8d70300fa0ebb36b37afbafc8f69101296bbd32376a77f8e16c828f2a8c5dc87e6d53acb9cf520",
          "sha256": "6bb423ff6a0d54e940e2c31f78b71d6e94316cc7fc165afaa0734f5fe31ef1bd",
          "sha1": "5c5e2192c8c2304e1036062c9d6da3789fd635ff",
          "md5": "38d1b7b4dd4db4989621255df3c74ddb"
        }
      ]
    },
    {
      "name": "-runtime",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "io.mockk",
          "module": "mockk-agent-jvm",
          "version": {
            "requires": "1.12.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "io.mockk",
          "module": "mockk-common",
          "version": {
            "requires": "1.12.2"
          }
        },
        {
          "group": "io.mockk",
          "module": "mockk-dsl-jvm",
          "version": {
            "requires": "1.12.2"
          }
        }
      ],
      "files": [
        {
          "name": "mockk-1.12.2.jar",
          "url": "mockk-1.12.2.jar",
          "size": 535748,
          "sha512": "a9002c60c58d91238a242fe2b852a1972accbf350403c0ea6e8d70300fa0ebb36b37afbafc8f69101296bbd32376a77f8e16c828f2a8c5dc87e6d53acb9cf520",
          "sha256": "6bb423ff6a0d54e940e2c31f78b71d6e94316cc7fc165afaa0734f5fe31ef1bd",
          "sha1": "5c5e2192c8c2304e1036062c9d6da3789fd635ff",
          "md5": "38d1b7b4dd4db4989621255df3c74ddb"
        }
      ]
    }
  ]
}
