{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.navigation",
    "module": "navigation-common",
    "version": "2.5.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5-20220421031748+0000"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.5.1"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-ktx",
          "version": {
            "requires": "2.5.1"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-savedstate",
          "version": {
            "requires": "2.5.1"
          }
        },
        {
          "group": "androidx.savedstate",
          "module": "savedstate-ktx",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "navigation-common-2.5.3.aar",
          "url": "navigation-common-2.5.3.aar",
          "size": 155950,
          "sha512": "b4f501f409a15d6b1bcf97aead1a8eac7b6c81dadb14215c7249487147cfc5394ffac964235bd551bd85b9be21fd3e0726acb9eb4229982a705da84f049cf8e7",
          "sha256": "841406807a7c2254c66460bfb71e65a112a95c84ecd6253302b3657f83332026",
          "sha1": "eac1bdefaebb4a860fa661243a599a0abfe34cda",
          "md5": "0fd99cd662b3613f6e668a6e5916a562"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.collection",
          "module": "collection-ktx",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.5.1"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-ktx",
          "version": {
            "requires": "2.5.1"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-savedstate",
          "version": {
            "requires": "2.5.1"
          }
        },
        {
          "group": "androidx.savedstate",
          "module": "savedstate-ktx",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "navigation-common-2.5.3.aar",
          "url": "navigation-common-2.5.3.aar",
          "size": 155950,
          "sha512": "b4f501f409a15d6b1bcf97aead1a8eac7b6c81dadb14215c7249487147cfc5394ffac964235bd551bd85b9be21fd3e0726acb9eb4229982a705da84f049cf8e7",
          "sha256": "841406807a7c2254c66460bfb71e65a112a95c84ecd6253302b3657f83332026",
          "sha1": "eac1bdefaebb4a860fa661243a599a0abfe34cda",
          "md5": "0fd99cd662b3613f6e668a6e5916a562"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "navigation-common-2.5.3-sources.jar",
          "url": "navigation-common-2.5.3-sources.jar",
          "size": 54874,
          "sha512": "862c0be71f12a6f62a5fd874cd2c996ccdf74813637cdfac24ca479dfab1421f08afa92b04ea1a640908250d203dc85f453a5bf3041644360c90274bfb201600",
          "sha256": "a775c00223af5ca08949d75165877f9b6582e6eb018d1f131bc7288e8de4d1df",
          "sha1": "f1d0bca09bca0aefde801761736f097f6710c803",
          "md5": "bd0a87fcf266ca4f83a361f68fd7b9ed"
        }
      ]
    }
  ]
}