{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.compose.ui",
    "module": "ui",
    "version": "1.1.0-beta01",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-saveable",
          "version": {
            "requires": "1.1.0-beta01"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-geometry",
          "version": {
            "requires": "1.1.0-beta01"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-graphics",
          "version": {
            "requires": "1.1.0-beta01"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-text",
          "version": {
            "requires": "1.1.0-beta01"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-unit",
          "version": {
            "requires": "1.1.0-beta01"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "ui-1.1.0-beta01.aar",
          "url": "ui-1.1.0-beta01.aar",
          "size": 3980943,
          "sha512": "d13ad7845c20a5ce15b2b43f4e85735b9d3225e068161e36b845c32ee48ebbeb0e04fccc89ba05ea0b641786472b329eeda1ac63572051300f70728c035eb4d6",
          "sha256": "b3549877b31f3e3b48f14d6a17972c90d79f6ef113be25036b90fd6bed35e211",
          "sha1": "779e382926c428b9d098cc47b9e081c09b66e815",
          "md5": "39f4396a5750645cf37266ffc07e6965"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-saveable",
          "version": {
            "requires": "1.1.0-beta01"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-geometry",
          "version": {
            "requires": "1.1.0-beta01"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-graphics",
          "version": {
            "requires": "1.1.0-beta01"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-text",
          "version": {
            "requires": "1.1.0-beta01"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-unit",
          "version": {
            "requires": "1.1.0-beta01"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.5.31"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.5.2"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.1.0-beta01"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-util",
          "version": {
            "requires": "1.1.0-beta01"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.5.31"
          }
        },
        {
          "group": "androidx.autofill",
          "module": "autofill",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.5.2"
          }
        },
        {
          "group": "androidx.savedstate",
          "module": "savedstate",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-common-java8",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "androidx.profileinstaller",
          "module": "profileinstaller",
          "version": {
            "requires": "1.1.0-beta01"
          }
        }
      ],
      "files": [
        {
          "name": "ui-1.1.0-beta01.aar",
          "url": "ui-1.1.0-beta01.aar",
          "size": 3980943,
          "sha512": "d13ad7845c20a5ce15b2b43f4e85735b9d3225e068161e36b845c32ee48ebbeb0e04fccc89ba05ea0b641786472b329eeda1ac63572051300f70728c035eb4d6",
          "sha256": "b3549877b31f3e3b48f14d6a17972c90d79f6ef113be25036b90fd6bed35e211",
          "sha1": "779e382926c428b9d098cc47b9e081c09b66e815",
          "md5": "39f4396a5750645cf37266ffc07e6965"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ui-1.1.0-beta01-sources.jar",
          "url": "ui-1.1.0-beta01-sources.jar",
          "size": 466222,
          "sha512": "f96a5e8862119b282323decec3aa092f142341b30f50e78cb4ca6d69aba087e31c6d418d6aede54b8c48bcb60535086e3b0b58215bacc32666c5efa47606cac5",
          "sha256": "fb7364700e868b15c412d1739728eedefd23c12da7ccf33468d64145da21ac36",
          "sha1": "929b5583a3260ccf2170955c25da5bd091d1fb1b",
          "md5": "c9e17e6c6c9020084bd64058e73b8e39"
        }
      ]
    }
  ]
}
