{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.activity",
    "module": "activity-compose",
    "version": "1.5.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.activity",
          "module": "activity-ktx",
          "version": {
            "requires": "1.5.1"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-saveable",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.0.1"
          }
        }
      ],
      "files": [
        {
          "name": "activity-compose-1.5.1.aar",
          "url": "activity-compose-1.5.1.aar",
          "size": 1048414,
          "sha512": "bb4caf5462dc68014c1825c2c674652848f38b1f379c51c1f3319546c41192462868a09c5e65855aa3781a3657ee30b2bc3314bd2646764ad4c15e17f201d80e",
          "sha256": "8374138f15251cc3ed375425599e94a36038c05cf877f877281ae019b95b844a",
          "sha1": "64f3b71432abfde764edea254eff4d92236c1b15",
          "md5": "2b6deaddfeae4c572737a197c05f7660"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.activity",
          "module": "activity-ktx",
          "version": {
            "requires": "1.5.1"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-saveable",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-common-java8",
          "version": {
            "requires": "2.5.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "activity-compose-1.5.1.aar",
          "url": "activity-compose-1.5.1.aar",
          "size": 1048414,
          "sha512": "bb4caf5462dc68014c1825c2c674652848f38b1f379c51c1f3319546c41192462868a09c5e65855aa3781a3657ee30b2bc3314bd2646764ad4c15e17f201d80e",
          "sha256": "8374138f15251cc3ed375425599e94a36038c05cf877f877281ae019b95b844a",
          "sha1": "64f3b71432abfde764edea254eff4d92236c1b15",
          "md5": "2b6deaddfeae4c572737a197c05f7660"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "activity-compose-1.5.1-sources.jar",
          "url": "activity-compose-1.5.1-sources.jar",
          "size": 6741,
          "sha512": "bb2d87bb2273480822c947d4ad20f9d2a6f40e40cd18be1ffd6ff2ef1131ab2f2891adfa8688dfb3a273242ceee76dd07fc0800e117251d7a544c165fe9464fa",
          "sha256": "8a8d020c5a4e63652afc4c70208cb2249fb723b447bd0cf935c781abe245e361",
          "sha1": "e9bce564b65bcfa2669ff44af6c578a3dea517dc",
          "md5": "d1a023f97ca873221d90ce4ee8a02b36"
        }
      ]
    }
  ]
}