{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.navigation",
    "module": "navigation-common-ktx",
    "version": "2.5.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5-20220421031748+0000"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.navigation",
          "module": "navigation-common",
          "version": {
            "requires": "2.5.2"
          }
        }
      ],
      "files": [
        {
          "name": "navigation-common-ktx-2.5.2.aar",
          "url": "navigation-common-ktx-2.5.2.aar",
          "size": 1771,
          "sha512": "b8c3f585cb41867fe6d246037e2d570845134efaacf5fc4d2b93200a7cba7175b0b2b5eafb182b43d63c82e53cc73580989f7c1b3064013648d4cd59a5622a77",
          "sha256": "cb24d6496077f87043d8ee489a5e10d240ce0604aeeeb22398fd3fca0caa3e84",
          "sha1": "e34a8619d92d7219c2e4b2debbb215259eb75e89",
          "md5": "103c31afb51f5e0d188104bbc291781c"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.navigation",
          "module": "navigation-common",
          "version": {
            "requires": "2.5.2"
          }
        }
      ],
      "files": [
        {
          "name": "navigation-common-ktx-2.5.2.aar",
          "url": "navigation-common-ktx-2.5.2.aar",
          "size": 1771,
          "sha512": "b8c3f585cb41867fe6d246037e2d570845134efaacf5fc4d2b93200a7cba7175b0b2b5eafb182b43d63c82e53cc73580989f7c1b3064013648d4cd59a5622a77",
          "sha256": "cb24d6496077f87043d8ee489a5e10d240ce0604aeeeb22398fd3fca0caa3e84",
          "sha1": "e34a8619d92d7219c2e4b2debbb215259eb75e89",
          "md5": "103c31afb51f5e0d188104bbc291781c"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "navigation-common-ktx-2.5.2-sources.jar",
          "url": "navigation-common-ktx-2.5.2-sources.jar",
          "size": 261,
          "sha512": "747d2f00a7f5f379582e33e452f30f3a25732a510971d9ed5161355bf7ef0fc507fef30883960dbfc780d36b6e8215fba01086b4ee053358805686e2f2c1aa85",
          "sha256": "69e1a62e5752ca3f43fb1607f161379bbe88b64af89c1a543c126160adf7cc53",
          "sha1": "5b8f86fea035328fc9e8c660773037a3401ce25f",
          "md5": "e7e9f45eb9d74540092920528bb0abf0"
        }
      ]
    }
  ]
}