{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.room",
    "module": "room-compiler-processing",
    "version": "2.4.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "com.squareup",
          "module": "javapoet",
          "version": {
            "requires": "1.13.0"
          }
        },
        {
          "group": "com.squareup",
          "module": "kotlinpoet",
          "version": {
            "requires": "1.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "room-compiler-processing-2.4.2.jar",
          "url": "room-compiler-processing-2.4.2.jar",
          "size": 879151,
          "sha512": "85974ddf16de392de3b67bc00897b9d10cf6153f581ed0fad182f64dcfe71002eba0ddaac440b8cf460c66d3b975c0d20e12b72085baa23856be483afe5fa562",
          "sha256": "e2d8462db15394945f5fe0be69792e5c25399a54d2fe17c6a954845e70f06377",
          "sha1": "7d69eb38c3377910327c57e1e49367e8f5bad833",
          "md5": "97b241f1da034d389f5f7cbe55b7f097"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "29.0-jre"
          }
        },
        {
          "group": "com.google.auto",
          "module": "auto-common",
          "version": {
            "requires": "0.11"
          }
        },
        {
          "group": "com.google.auto.value",
          "module": "auto-value-annotations",
          "version": {
            "requires": "1.6.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-metadata-jvm",
          "version": {
            "requires": "0.3.0"
          }
        },
        {
          "group": "com.intellij",
          "module": "annotations",
          "version": {
            "requires": "12.0"
          }
        },
        {
          "group": "com.google.devtools.ksp",
          "module": "symbol-processing-api",
          "version": {
            "requires": "1.6.10-1.0.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "com.squareup",
          "module": "javapoet",
          "version": {
            "requires": "1.13.0"
          }
        },
        {
          "group": "com.squareup",
          "module": "kotlinpoet",
          "version": {
            "requires": "1.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "room-compiler-processing-2.4.2.jar",
          "url": "room-compiler-processing-2.4.2.jar",
          "size": 879151,
          "sha512": "85974ddf16de392de3b67bc00897b9d10cf6153f581ed0fad182f64dcfe71002eba0ddaac440b8cf460c66d3b975c0d20e12b72085baa23856be483afe5fa562",
          "sha256": "e2d8462db15394945f5fe0be69792e5c25399a54d2fe17c6a954845e70f06377",
          "sha1": "7d69eb38c3377910327c57e1e49367e8f5bad833",
          "md5": "97b241f1da034d389f5f7cbe55b7f097"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "room-compiler-processing-2.4.2-sources.jar",
          "url": "room-compiler-processing-2.4.2-sources.jar",
          "size": 185511,
          "sha512": "8262a089c4078661beac5d4d6943814752c33f066836b85fe966b3bb385bb0e41af7cbaac99cd9b82dc0f2e4c9f43313e114e654b7cc5ace77efa01351f13218",
          "sha256": "b57204d3ae8f2678dc961ad416848072641b2d4f237a135c14f6ed291ff8c624",
          "sha1": "be765705743659fa001a02310c88fafdaf9f59d1",
          "md5": "93e33b72b9ac77649c59951fc700147a"
        }
      ]
    }
  ]
}
