{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.compose.ui",
    "module": "ui-unit",
    "version": "1.0.0-beta03",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.1",
      "buildId:": "7217131"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.compose.ui",
          "module": "ui-geometry",
          "version": {
            "requires": "1.0.0-beta03"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "ui-unit-1.0.0-beta03.aar",
          "url": "ui-unit-1.0.0-beta03.aar",
          "size": 56855,
          "sha512": "3abfac5a9a9baf3d9fde1b6c828f22ef7fc7401da0e96356a9fbea97267b7541be899c2d7ab0b80a35c2817c147ca0b6b5794d26a81bb57c1b11ec0b60746077",
          "sha256": "886206123433a0b07f36a67bfac3d6ea36086305658d4e4c799527116732ac28",
          "sha1": "61346404265c80d6532b890d9672f980692d0aeb",
          "md5": "8e24c9c7ae01865850e6b739a7ac618f"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.compose.ui",
          "module": "ui-geometry",
          "version": {
            "requires": "1.0.0-beta03"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.31"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.0.0-beta03"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-util",
          "version": {
            "requires": "1.0.0-beta03"
          }
        }
      ],
      "files": [
        {
          "name": "ui-unit-1.0.0-beta03.aar",
          "url": "ui-unit-1.0.0-beta03.aar",
          "size": 56855,
          "sha512": "3abfac5a9a9baf3d9fde1b6c828f22ef7fc7401da0e96356a9fbea97267b7541be899c2d7ab0b80a35c2817c147ca0b6b5794d26a81bb57c1b11ec0b60746077",
          "sha256": "886206123433a0b07f36a67bfac3d6ea36086305658d4e4c799527116732ac28",
          "sha1": "61346404265c80d6532b890d9672f980692d0aeb",
          "md5": "8e24c9c7ae01865850e6b739a7ac618f"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ui-unit-1.0.0-beta03-sources.jar",
          "url": "ui-unit-1.0.0-beta03-sources.jar",
          "size": 21509,
          "sha512": "71fde7b0627ab140cdea470270477a192597b6401634a0ef7ea5cff928e9fcb624359d758c42dc33d0f30dac5407cf350f653fe19a8ba1c2fd34af4a16bf67fc",
          "sha256": "ebc919f9da0f0402076e1c80495f93d223214ca72938fb5468c1ef7703be9f63",
          "sha1": "0191501f8d51738467a8110b8a6b6a62e6d05566",
          "md5": "4e6fefea5ebd856f223b20de421de12a"
        }
      ]
    }
  ]
}
