{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.compose.ui",
    "module": "ui-geometry",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "ui-geometry-1.0.0.aar",
          "url": "ui-geometry-1.0.0.aar",
          "size": 37320,
          "sha512": "bb75b7d566effb6f66c96a047f0098754a87846e38204b55882cf87a862ccfea37f4805c423382bda806e8a5010ee86528b5e92cdebfbee94f8f8be1cb0d9269",
          "sha256": "da5b6793c694beca64efc165afb5831ebb34a0c9bafb9ef7ee636a3b7de910d0",
          "sha1": "2c571d7f24e7294945eedf0f876e197c30f3469b",
          "md5": "efdf5c1608c51d1ff8a2a90c7007429c"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-util",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.5.10"
          }
        }
      ],
      "files": [
        {
          "name": "ui-geometry-1.0.0.aar",
          "url": "ui-geometry-1.0.0.aar",
          "size": 37320,
          "sha512": "bb75b7d566effb6f66c96a047f0098754a87846e38204b55882cf87a862ccfea37f4805c423382bda806e8a5010ee86528b5e92cdebfbee94f8f8be1cb0d9269",
          "sha256": "da5b6793c694beca64efc165afb5831ebb34a0c9bafb9ef7ee636a3b7de910d0",
          "sha1": "2c571d7f24e7294945eedf0f876e197c30f3469b",
          "md5": "efdf5c1608c51d1ff8a2a90c7007429c"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ui-geometry-1.0.0-sources.jar",
          "url": "ui-geometry-1.0.0-sources.jar",
          "size": 17854,
          "sha512": "0eddfd791e910b05fcdc80ee048090628ad571bd83d58dd77e10d3e32a1a17e52f085e924b61c43f498578505ed03cec5d68099c45590918c85ad4b58d06f9c8",
          "sha256": "296a33c82f908a43b450389274d203465d2d14f6cab364e9c390411924cde988",
          "sha1": "be1f2ac9907309bae983a9ff69646a811493ebbf",
          "md5": "c505070ebf86fbbed3cf001c9ee9b99b"
        }
      ]
    }
  ]
}
