{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.navigation",
    "module": "navigation-ui-ktx",
    "version": "2.5.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5-20220421031748+0000"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.navigation",
          "module": "navigation-runtime-ktx",
          "version": {
            "requires": "2.5.0"
          },
          "reason": "Mirror navigation-ui dependency graph for -ktx artifacts"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-ui",
          "version": {
            "requires": "2.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "navigation-ui-ktx-2.5.0.aar",
          "url": "navigation-ui-ktx-2.5.0.aar",
          "size": 1767,
          "sha512": "bcf023032a3ccc70711d91862ef77777295560eeea5502519fb75b86b1747beb1c91f738e804c7edc25c9034fc7964fd4671db0116071f29504dda8789da1905",
          "sha256": "567cc200f1e70436d66e53cc63cf80198d2194049ba2d60a5f975ac8b5b4343a",
          "sha1": "620e589e8e318ca5bea716bcd9a76dc86a265359",
          "md5": "736f05e56a68e162bd69184944359748"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.navigation",
          "module": "navigation-runtime-ktx",
          "version": {
            "requires": "2.5.0"
          },
          "reason": "Mirror navigation-ui dependency graph for -ktx artifacts"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-ui",
          "version": {
            "requires": "2.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "navigation-ui-ktx-2.5.0.aar",
          "url": "navigation-ui-ktx-2.5.0.aar",
          "size": 1767,
          "sha512": "bcf023032a3ccc70711d91862ef77777295560eeea5502519fb75b86b1747beb1c91f738e804c7edc25c9034fc7964fd4671db0116071f29504dda8789da1905",
          "sha256": "567cc200f1e70436d66e53cc63cf80198d2194049ba2d60a5f975ac8b5b4343a",
          "sha1": "620e589e8e318ca5bea716bcd9a76dc86a265359",
          "md5": "736f05e56a68e162bd69184944359748"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "navigation-ui-ktx-2.5.0-sources.jar",
          "url": "navigation-ui-ktx-2.5.0-sources.jar",
          "size": 261,
          "sha512": "747d2f00a7f5f379582e33e452f30f3a25732a510971d9ed5161355bf7ef0fc507fef30883960dbfc780d36b6e8215fba01086b4ee053358805686e2f2c1aa85",
          "sha256": "69e1a62e5752ca3f43fb1607f161379bbe88b64af89c1a543c126160adf7cc53",
          "sha1": "5b8f86fea035328fc9e8c660773037a3401ce25f",
          "md5": "e7e9f45eb9d74540092920528bb0abf0"
        }
      ]
    }
  ]
}