{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.work",
    "module": "work-rxjava2",
    "version": "2.7.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.work",
          "module": "work-runtime",
          "version": {
            "requires": "2.7.1"
          }
        },
        {
          "group": "io.reactivex.rxjava2",
          "module": "rxjava",
          "version": {
            "requires": "2.2.9"
          }
        }
      ],
      "files": [
        {
          "name": "work-rxjava2-2.7.1.aar",
          "url": "work-rxjava2-2.7.1.aar",
          "size": 4358,
          "sha512": "2d28e8e9e2c46f37f9dcace8e98ffd984442d1e99408e5af739512c317d2dda88b5f4a8986b3714b07dc8fee71f8b28aa399ea22b53cbf8c40a16b1afef62bb1",
          "sha256": "48d23d42765ce9e0cb290dab7b500d6950fad1d47fe129c1d9a3e01037dc33f3",
          "sha1": "28c736c9f88920e9e279324a4743dbe8986f0c1b",
          "md5": "baeb040317a9c5c540dac6b65d742e7e"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.work",
          "module": "work-runtime",
          "version": {
            "requires": "2.7.1"
          }
        },
        {
          "group": "io.reactivex.rxjava2",
          "module": "rxjava",
          "version": {
            "requires": "2.2.9"
          }
        }
      ],
      "files": [
        {
          "name": "work-rxjava2-2.7.1.aar",
          "url": "work-rxjava2-2.7.1.aar",
          "size": 4358,
          "sha512": "2d28e8e9e2c46f37f9dcace8e98ffd984442d1e99408e5af739512c317d2dda88b5f4a8986b3714b07dc8fee71f8b28aa399ea22b53cbf8c40a16b1afef62bb1",
          "sha256": "48d23d42765ce9e0cb290dab7b500d6950fad1d47fe129c1d9a3e01037dc33f3",
          "sha1": "28c736c9f88920e9e279324a4743dbe8986f0c1b",
          "md5": "baeb040317a9c5c540dac6b65d742e7e"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "work-rxjava2-2.7.1-sources.jar",
          "url": "work-rxjava2-2.7.1-sources.jar",
          "size": 2879,
          "sha512": "60dcd3277dd49768d27d9d504d9f4c374ed87bd17ac135f4d444cd13f56c3599b4266b875e3174213d0cfe3077935743abb11e5d979c4177131faef3538b6927",
          "sha256": "5a85eb6ac6c99b91619c580c8f72cbdf5804da953c2db7f9f6e11d307f1bdd8e",
          "sha1": "6dac8cc9a24299bb3516ed9011e516c3c0c87160",
          "md5": "bc2e1ebe1db4040a586f7d67fe80bb30"
        }
      ]
    }
  ]
}
