{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.compose.runtime",
    "module": "runtime-saveable",
    "version": "1.1.0-beta01",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.1.0-beta01"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "runtime-saveable-1.1.0-beta01.aar",
          "url": "runtime-saveable-1.1.0-beta01.aar",
          "size": 1064861,
          "sha512": "7471b999174907496f22d1b613b500b6fb0b003fb8d79621eacf47d963116f5b5fe76ee7c05ac06d30236a2671b236534c31671e93d68079e6c08a877b0e4002",
          "sha256": "05194250bfbcfca5fa017e525b8a92be0e60bb01853088edddd51cd255864a3b",
          "sha1": "038f89887f270e99f3ec47fd64e16c57cad19653",
          "md5": "0118c396cc90529acf6ae8af8abc9fad"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.1.0-beta01"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.5.31"
          }
        }
      ],
      "files": [
        {
          "name": "runtime-saveable-1.1.0-beta01.aar",
          "url": "runtime-saveable-1.1.0-beta01.aar",
          "size": 1064861,
          "sha512": "7471b999174907496f22d1b613b500b6fb0b003fb8d79621eacf47d963116f5b5fe76ee7c05ac06d30236a2671b236534c31671e93d68079e6c08a877b0e4002",
          "sha256": "05194250bfbcfca5fa017e525b8a92be0e60bb01853088edddd51cd255864a3b",
          "sha1": "038f89887f270e99f3ec47fd64e16c57cad19653",
          "md5": "0118c396cc90529acf6ae8af8abc9fad"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "runtime-saveable-1.1.0-beta01-sources.jar",
          "url": "runtime-saveable-1.1.0-beta01-sources.jar",
          "size": 10757,
          "sha512": "7df6218202b1a9a28aab2a1ba30ab712af7822cd7809bb0d933a55f685d2ea11e89080c94b78c3d441b234b0e7f6b0be5506875e9ff6d15de325590e5a22d143",
          "sha256": "fd8679b995c1e70d1756c852b121c5bbbb7037f17cb806e5c0c2eb11e3223f8c",
          "sha1": "b77cfebbb149996dd8dc989531bbea1844c74ebc",
          "md5": "30221aa91da1d39bf8f22478735df22c"
        }
      ]
    }
  ]
}
