{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.compose.ui",
    "module": "ui-geometry",
    "version": "1.0.0-beta03",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.1",
      "buildId:": "7217131"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "ui-geometry-1.0.0-beta03.aar",
          "url": "ui-geometry-1.0.0-beta03.aar",
          "size": 37377,
          "sha512": "dca6b30dad518de780d3f9b539066ececd8d84de9a7af0c03e70603178b56580af095600a59947e22a1ad5e80cd10fefe153221fdacbb843a70b48e921ee3cab",
          "sha256": "5a27ac60d83a091850310273db3b50f51ff16a2874bd964746a546edf5dd3af4",
          "sha1": "8eecee0a22c1b549efe1da5c6fc6f8c7b7a23887",
          "md5": "02333b5803660891eb217d5a03b45505"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.0.0-beta03"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-util",
          "version": {
            "requires": "1.0.0-beta03"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.31"
          }
        }
      ],
      "files": [
        {
          "name": "ui-geometry-1.0.0-beta03.aar",
          "url": "ui-geometry-1.0.0-beta03.aar",
          "size": 37377,
          "sha512": "dca6b30dad518de780d3f9b539066ececd8d84de9a7af0c03e70603178b56580af095600a59947e22a1ad5e80cd10fefe153221fdacbb843a70b48e921ee3cab",
          "sha256": "5a27ac60d83a091850310273db3b50f51ff16a2874bd964746a546edf5dd3af4",
          "sha1": "8eecee0a22c1b549efe1da5c6fc6f8c7b7a23887",
          "md5": "02333b5803660891eb217d5a03b45505"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ui-geometry-1.0.0-beta03-sources.jar",
          "url": "ui-geometry-1.0.0-beta03-sources.jar",
          "size": 17784,
          "sha512": "96f0e7c79db06e17a839432ca1c80b2e54bb66e147d9eda9c5a5a0eb6af2d113b939605da39ca461df8715d895aed49b417069bd7d41d1dea055f5458a4c0e25",
          "sha256": "0fd8ee85835552569faa61935dd186397d087494005d8fa07576e51ef4945260",
          "sha1": "a2466c92f4dc775a6d59e58593d5b5c741b5fe76",
          "md5": "32f1e337fc0230cff2c1f791bb6ae366"
        }
      ]
    }
  ]
}
