{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.compose.ui",
    "module": "ui-unit",
    "version": "1.1.0-beta01",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.compose.ui",
          "module": "ui-geometry",
          "version": {
            "requires": "1.1.0-beta01"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "ui-unit-1.1.0-beta01.aar",
          "url": "ui-unit-1.1.0-beta01.aar",
          "size": 65568,
          "sha512": "40dee81a72af92ce2acebc34bc5034685d9277e4f4cc03ef63af71ba2085c7c3411d76256fd3279a183dcbb893cfbcdb3a53176f332a918c68e406ae3a344bb3",
          "sha256": "48cb7b8fbeee4acc27db358255995a0db891e1fe138bb8bf11073d4b579bba10",
          "sha1": "a868ba61a3fbefcca532f4c347174000761f6263",
          "md5": "00af6393ff18fc5a5cddf22770bf84ad"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.compose.ui",
          "module": "ui-geometry",
          "version": {
            "requires": "1.1.0-beta01"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.5.31"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.1.0-beta01"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-util",
          "version": {
            "requires": "1.1.0-beta01"
          }
        }
      ],
      "files": [
        {
          "name": "ui-unit-1.1.0-beta01.aar",
          "url": "ui-unit-1.1.0-beta01.aar",
          "size": 65568,
          "sha512": "40dee81a72af92ce2acebc34bc5034685d9277e4f4cc03ef63af71ba2085c7c3411d76256fd3279a183dcbb893cfbcdb3a53176f332a918c68e406ae3a344bb3",
          "sha256": "48cb7b8fbeee4acc27db358255995a0db891e1fe138bb8bf11073d4b579bba10",
          "sha1": "a868ba61a3fbefcca532f4c347174000761f6263",
          "md5": "00af6393ff18fc5a5cddf22770bf84ad"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ui-unit-1.1.0-beta01-sources.jar",
          "url": "ui-unit-1.1.0-beta01-sources.jar",
          "size": 23326,
          "sha512": "76d343176a2ffdbf575b9f59577c62dd4092dabc18072b23bf64b910156cf5d179adfc3f76e2bbd7846d861cea69d8ce6ae7180aabcac11c9c6293c1e83ef8da",
          "sha256": "918a3c500e20a0bf2cb92c0723a6ab0483bce7c75a59e5ebd29566133f996e0d",
          "sha1": "e7d13bf2b7360ed393166e3f825368e71e9fcd3f",
          "md5": "a142c5aa2793c83c1db39421e9d41708"
        }
      ]
    }
  ]
}
