{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.databinding",
    "module": "databinding-runtime",
    "version": "7.1.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.databinding",
          "module": "databinding-common",
          "version": {
            "requires": "7.1.3"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "7.1.3"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime",
          "version": {
            "requires": "2.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "databinding-runtime-7.1.3.aar",
          "url": "databinding-runtime-7.1.3.aar",
          "size": 62701,
          "sha512": "dc9ec2a36c0fc9f66d50a37eabab44b9755cc9d532e913fea95f28eb45aa6eb21798a450ab257339def41e0012c9a3d215c5a38b15c1cc524eff0b8f8928f082",
          "sha256": "b113aafa3d2077946f0ef32a117a8c416a7d04814e6cab17742c8745d98d4aca",
          "sha1": "e2f2003777f3eeec18ba2f9af912215fdd05e9c8",
          "md5": "583eecfcb6f4b745c8f8a0075a8d5ad1"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.collection",
          "module": "collection",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-common",
          "version": {
            "requires": "7.1.3"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "7.1.3"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime",
          "version": {
            "requires": "2.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "databinding-runtime-7.1.3.aar",
          "url": "databinding-runtime-7.1.3.aar",
          "size": 62701,
          "sha512": "dc9ec2a36c0fc9f66d50a37eabab44b9755cc9d532e913fea95f28eb45aa6eb21798a450ab257339def41e0012c9a3d215c5a38b15c1cc524eff0b8f8928f082",
          "sha256": "b113aafa3d2077946f0ef32a117a8c416a7d04814e6cab17742c8745d98d4aca",
          "sha1": "e2f2003777f3eeec18ba2f9af912215fdd05e9c8",
          "md5": "583eecfcb6f4b745c8f8a0075a8d5ad1"
        }
      ]
    }
  ]
}
