{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.hilt",
    "module": "hilt-common",
    "version": "1.0.0-alpha03",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId:": "7094152"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "hilt-common-1.0.0-alpha03.jar",
          "url": "hilt-common-1.0.0-alpha03.jar",
          "size": 4045,
          "sha512": "8d339095fe4f72e86b05e180e50be51a8ba1b49e4b418d2152b9edea7096a6010d92793d912ca7fe2e9c59eb7fc0e69572e9c61de719dc39e1fdcdc79749a678",
          "sha256": "3e006cf15aeeeb0c2ff2ae5c2730d6f74a4b2aa12425c2068fb26e4cda43f617",
          "sha1": "90aeb66553da3c66ca5047835d9eb1fcf26dc10e",
          "md5": "660876ae0b356c08619b012b587cb734"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.dagger",
          "module": "hilt-core",
          "version": {
            "requires": "2.31-alpha"
          }
        }
      ],
      "files": [
        {
          "name": "hilt-common-1.0.0-alpha03.jar",
          "url": "hilt-common-1.0.0-alpha03.jar",
          "size": 4045,
          "sha512": "8d339095fe4f72e86b05e180e50be51a8ba1b49e4b418d2152b9edea7096a6010d92793d912ca7fe2e9c59eb7fc0e69572e9c61de719dc39e1fdcdc79749a678",
          "sha256": "3e006cf15aeeeb0c2ff2ae5c2730d6f74a4b2aa12425c2068fb26e4cda43f617",
          "sha1": "90aeb66553da3c66ca5047835d9eb1fcf26dc10e",
          "md5": "660876ae0b356c08619b012b587cb734"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "hilt-common-1.0.0-alpha03-sources.jar",
          "url": "hilt-common-1.0.0-alpha03-sources.jar",
          "size": 4194,
          "sha512": "e37f4c833d17e8ff4eab6a6402927e1c81a74534ed8842bd8cfc085cdc2b3f7ae2d0aecf29d2c6f89947f4dcf9e20cbc8fb4e9e204a0cdeca2e89e0a070b6ce2",
          "sha256": "4bba10f99841636932814bfa37dd9d7ead22b503615a64c9b0b434d680182cfc",
          "sha1": "f3c2e3335c3da98a75aa84d5b89ead1f1633282c",
          "md5": "0ea2273206d77909352fa5724d4ccf7d"
        }
      ]
    }
  ]
}
