{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.compose.ui",
    "module": "ui-tooling-preview",
    "version": "1.1.0-beta01",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.1.0-beta01"
          }
        }
      ],
      "files": [
        {
          "name": "ui-tooling-preview-1.1.0-beta01.aar",
          "url": "ui-tooling-preview-1.1.0-beta01.aar",
          "size": 11188,
          "sha512": "2ddc392724a9af5df1232d1f59cd2c7b1256c6ac1990b08ac8b93224db657f9c9aa9645da7459503d28d1dc7f77acaab510e2f4fa36c9b6519b2b2be3d3ef029",
          "sha256": "da29abfd69e99a5c9ae3851b4528ef6b3f22b286f5042fec1cb61f0cc6c5978e",
          "sha1": "2b6a61e558968f261dd770c56104cad1dadab9fa",
          "md5": "f21e9020088d6412a03a051aaacfca65"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.1.0-beta01"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.5.31"
          }
        }
      ],
      "files": [
        {
          "name": "ui-tooling-preview-1.1.0-beta01.aar",
          "url": "ui-tooling-preview-1.1.0-beta01.aar",
          "size": 11188,
          "sha512": "2ddc392724a9af5df1232d1f59cd2c7b1256c6ac1990b08ac8b93224db657f9c9aa9645da7459503d28d1dc7f77acaab510e2f4fa36c9b6519b2b2be3d3ef029",
          "sha256": "da29abfd69e99a5c9ae3851b4528ef6b3f22b286f5042fec1cb61f0cc6c5978e",
          "sha1": "2b6a61e558968f261dd770c56104cad1dadab9fa",
          "md5": "f21e9020088d6412a03a051aaacfca65"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ui-tooling-preview-1.1.0-beta01-sources.jar",
          "url": "ui-tooling-preview-1.1.0-beta01-sources.jar",
          "size": 7885,
          "sha512": "bcd81d5b29b6bb97f9aec76ed6c4679a7e0855f1784ec636ddc685b4af63cb1ee14fdd52082fd699c61f8d48d6ec3c7005e810805284960d19f57015ea4d617a",
          "sha256": "c33f94f7d8e56826e2183a37ddeb640513e7be77d05b50bd3ef35382a926167e",
          "sha1": "90bbc79411d268373f8af19c38292749d4b2b15b",
          "md5": "2f79011292ae7c0c0de042f4353a48d9"
        }
      ]
    }
  ]
}
