{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.compose.ui",
    "module": "ui-graphics",
    "version": "1.0.0-beta03",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.1",
      "buildId:": "7217131"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.2.0-beta01"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-unit",
          "version": {
            "requires": "1.0.0-beta03"
          }
        }
      ],
      "files": [
        {
          "name": "ui-graphics-1.0.0-beta03.aar",
          "url": "ui-graphics-1.0.0-beta03.aar",
          "size": 326303,
          "sha512": "7f6afa802c21334b3671fd55014d64fcfab386c6c5de82711574203184e477dc564aab98679572e0dad240ffaab7ae602a28a723393bdfde739baf4ad7aba66b",
          "sha256": "de0049466a031faf2927334df489541c60256aca5519f722dae1140b52385df4",
          "sha1": "7b9eb7a0b318ca49d916cc7b7753d28d65ab64f1",
          "md5": "08b4238d745d6a95a3246257d518e241"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.2.0-beta01"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-unit",
          "version": {
            "requires": "1.0.0-beta03"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.0.0-beta03"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-util",
          "version": {
            "requires": "1.0.0-beta03"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.31"
          }
        }
      ],
      "files": [
        {
          "name": "ui-graphics-1.0.0-beta03.aar",
          "url": "ui-graphics-1.0.0-beta03.aar",
          "size": 326303,
          "sha512": "7f6afa802c21334b3671fd55014d64fcfab386c6c5de82711574203184e477dc564aab98679572e0dad240ffaab7ae602a28a723393bdfde739baf4ad7aba66b",
          "sha256": "de0049466a031faf2927334df489541c60256aca5519f722dae1140b52385df4",
          "sha1": "7b9eb7a0b318ca49d916cc7b7753d28d65ab64f1",
          "md5": "08b4238d745d6a95a3246257d518e241"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ui-graphics-1.0.0-beta03-sources.jar",
          "url": "ui-graphics-1.0.0-beta03-sources.jar",
          "size": 146871,
          "sha512": "bca904f611179f998c04392f88f1713d0a703006044ab8fdffecb15aee13887b405e8317a4f2fafd132e86ba8c7e9ecd9c3458eb66795880d929d0683a343f96",
          "sha256": "00c56737e8f033c2126ca99d86ec34d24b249bd3ca8bdb9fa8038e9904986c3b",
          "sha1": "796c3180853e872e81bac04649364553527a231e",
          "md5": "34ea621e913362e388bf83e06c402997"
        }
      ]
    }
  ]
}
