{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.databinding",
    "module": "databinding-compiler",
    "version": "7.1.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "databinding-compiler-7.1.3.jar",
          "url": "databinding-compiler-7.1.3.jar",
          "size": 1192223,
          "sha512": "0bb99bbdd9aea0e24b9a7311b933123f1b30d8af61de04a47ea9ba313006a11b5cd009b84926ebe21765f9834bf9b88d29ab6fef1c214459ee1ecaf9f22cad75",
          "sha256": "d9b7a0645ad488a0527ff1c43b5cf21ad74f8f52dcf8d7ea92329e20c4218cf0",
          "sha1": "76b51075d6d3aad926428b183d85a653a7b0e78d",
          "md5": "8d23259b4f0a5dad3c7fdbae527d2aa1"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "androidx.databinding",
          "module": "databinding-compiler-common",
          "version": {
            "requires": "7.1.3"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-common",
          "version": {
            "requires": "7.1.3"
          }
        },
        {
          "group": "com.android.tools",
          "module": "annotations",
          "version": {
            "requires": "30.1.3"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "com.google.auto",
          "module": "auto-common",
          "version": {
            "requires": "0.10"
          }
        },
        {
          "group": "com.squareup",
          "module": "javapoet",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.6"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1-jre"
          }
        },
        {
          "group": "commons-io",
          "module": "commons-io",
          "version": {
            "requires": "2.4"
          }
        },
        {
          "group": "commons-codec",
          "module": "commons-codec",
          "version": {
            "requires": "1.10"
          }
        },
        {
          "group": "org.antlr",
          "module": "antlr4",
          "version": {
            "requires": "4.5.3"
          }
        },
        {
          "group": "com.googlecode.juniversalchardet",
          "module": "juniversalchardet",
          "version": {
            "requires": "1.0.3"
          }
        },
        {
          "group": "org.glassfish.jaxb",
          "module": "jaxb-runtime",
          "version": {
            "requires": "2.3.2"
          }
        }
      ],
      "files": [
        {
          "name": "databinding-compiler-7.1.3.jar",
          "url": "databinding-compiler-7.1.3.jar",
          "size": 1192223,
          "sha512": "0bb99bbdd9aea0e24b9a7311b933123f1b30d8af61de04a47ea9ba313006a11b5cd009b84926ebe21765f9834bf9b88d29ab6fef1c214459ee1ecaf9f22cad75",
          "sha256": "d9b7a0645ad488a0527ff1c43b5cf21ad74f8f52dcf8d7ea92329e20c4218cf0",
          "sha1": "76b51075d6d3aad926428b183d85a653a7b0e78d",
          "md5": "8d23259b4f0a5dad3c7fdbae527d2aa1"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "databinding-compiler-7.1.3-javadoc.jar",
          "url": "databinding-compiler-7.1.3-javadoc.jar",
          "size": 757637,
          "sha512": "861b019c64dd6d37bb23051fe796eef8364447e1b75929f74d990f0867d968de9da628587b68e3eeb7e770e553a7918507554ad0ad93c83fbe435deb65dc92bd",
          "sha256": "4797e8d58a1aa8083a29f06554613ec126bc15737a3306f12dcc9ba824eee665",
          "sha1": "8e1f1a43d800334a3afbf9ee5aa298900864f2d9",
          "md5": "bf7b2a5099b8c58056a5469f0368f121"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "databinding-compiler-7.1.3-sources.jar",
          "url": "databinding-compiler-7.1.3-sources.jar",
          "size": 569380,
          "sha512": "a5c0658a089dba737f58172574ceae38a5b06e02795b45ba91b8ac1aba7c376a662c5e991e8d6cc54c448065070575c179cdfdddf492886281146dfbb554255b",
          "sha256": "a90822737832108bcf1eea576a698f3c1de31c068ecee1b4fad6c0e1e7755062",
          "sha1": "6d9d0ac1359481864b62ee764e86578d6475dbd3",
          "md5": "7bf2f80673bca10dc2c85d02bfb0921f"
        }
      ]
    }
  ]
}
